language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install perl perl-debug
  - ./install-cctools.sh
install: "pip install -r requirements.txt"
env:
  - PYTHONPATH=$PWD/cctools/lib/python2.7/site-packages/
  - PATH=$PATH/:$PWD/cctools/bin/
before_script:
  - echo $PYTHONPATH
  - echo $PATH
script: nosetests --with-coverage --cover-package=slr
after_success:
  - coveralls
